# Generated by Django 3.2 on 2023-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-updated_at']},
        ),
    ]
